haircut/urls.py
from django.urls import path

from . import views
app_name = "haircut"
urlpatterns = [
     path('', views.home_page, name='home_page'),
]

salon/urls.py
from django.urls import include, path 
from django.contrib import admin

urlpatterns = [ 
     path('', include('haircut.urls')), 
     path('admin/', admin.site.urls),
]

haircut/models.py
from django.db import models

# Create your models here.
class Appointment(models.Model):
     time = models.CharField(max_length=180, null=True, blank=True)
     customer_name = models.CharField(max_length=180, null=True, blank=True)
     barber_name = models.CharField(max_length=180, null=True, blank=True)

haircut/views.py
from django.shortcuts import render
from .models import Appointment
def home_page(request):



    if request.method == "POST":

        time = request.POST['time']
        customer_name = request.POST['customer_name']
        barber_name = request.POST['barber_name']



        appointment_obj = Appointment.objects.create(
            time=time,
            customer_name=customer_name,
            barber_name=barber_name
        )
        all_appointments = Appointment.objects.all()
        context = {'appointments': all_appointments}


        return render(request, "haircut/home_page.html", context)


    if request.method == "GET":
        all_appointments = Appointment.objects.all()
        context = {'appointments': all_appointments}

        return render(request, 'haircut/home_page.html', context)

haircut/templates/haircut/home_page.html
<!DOCTYPE html>
<html>
<head>
 <title>Amazing Amy’s Barbershop</title>
</head>
<body>
 <!-- Site Header -->
 <h1>Amazing Amy’s Barbershop</h1>
 <p>A Fresh Cut You And Your Family!</p>

	<!-- Item 1 -->
	<p>frank 30rmb</p>
	<img src="https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=2859656346,4275554954&fm=27&gp=0.jpg">

	<!-- Item 2 -->
	<p>amy 40rmb</p>
	<img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1526485294501&di=a6c8db940182197db6a2e4baad1a8517&imgtype=0&src=http%3A%2F%2Fimgsrc.baidu.com%2Fimgad%2Fpic%2Fitem%2F1f178a82b9014a90faaf9e84a2773912b31bee72.jpg">

	<!-- Item 3 -->
	<p>jay 50rmb</p>
	<img src="https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=38426510,475451259&fm=27&gp=0.jpg">

 <!-- User Form -->
    <h1>Place Your Order</h1>
    <form action="{% url 'haircut:home_page' %} " method="POST">
        {% csrf_token %}
        <textarea placeholder="What Is Your Name" name="customer_name"></textarea><br>
        <input type="time" name="time" placeholder="Type Your time"><br>
        <input type="text" placeholder="Type Your Barber That You Want" name="barber_name" ><br>
        <input type="submit" value="Make Appointment">
    </form>

    {% for appointment in appointments %}
       <p> Customer Name: {{appointment.customer_name}}</p>
        <p>Barber Wanted: {{appointment.barber_name}}</p>
        <p>Time: {{appointment.time}}</p> <hr>
        
    {% endfor %}

    <h1>Your Order</h1>
    <p>time: {{time}}</p>
    <p>customer_name: {{customer_name}}</p>

</body>
</html>